<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.54" os="Windows 2008 R2" host="IDC1-VM-UFT12"><DocLocation><![CDATA[C:\Users\utpal\Desktop\Advantage_Shopping\Script]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Script]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:34]]></Time>
<TimeTick>1527009154</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "chrome",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome",1]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:34]]></Time>
<TimeTick>1527009154</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Login" SourceLine="-1" >
<Disp><![CDATA[Run "chrome",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Login" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:36]]></Time>
<TimeTick>1527009156</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:36]]></Time>
<TimeTick>1527009156</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[My account My Orders Sign.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:36]]></Time>
<TimeTick>1527009156</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Login" SourceLine="-1" >
<Disp><![CDATA[My account My Orders Sign.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["iDeliver"]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:37]]></Time>
<TimeTick>1527009157</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Login" SourceLine="-1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["iDeliver@1"]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:37]]></Time>
<TimeTick>1527009157</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Login" SourceLine="-1" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[sign_in_btnundefined.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:37]]></Time>
<TimeTick>1527009157</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Login" SourceLine="-1" >
<Disp><![CDATA[sign_in_btnundefined.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Login" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Login" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[User Login]]></Obj>
<Details ><![CDATA[User loggned in successfully]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:38]]></Time>
<TimeTick>1527009158</TimeTick>
<NodeArgs eType="User" icon="11" nRep="28" status="Passed" >
<Disp><![CDATA[User Login]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="5/22/2018 - 22:42:34" eTime="5/22/2018 - 22:42:46" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[Product_Select]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:46]]></Time>
<TimeTick>1527009166</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:46]]></Time>
<TimeTick>1527009166</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[SPEAKERS.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:46]]></Time>
<TimeTick>1527009166</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[SPEAKERS.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[SPEAKERS.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:46]]></Time>
<TimeTick>1527009166</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[SPEAKERS.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="33" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj ><![CDATA[Product Select]]></Obj>
<Details ><![CDATA[Click on the Product]]></Details>
<Time><![CDATA[5/22/2018 - 22:42:46]]></Time>
<TimeTick>1527009166</TimeTick>
<NodeArgs eType="User" icon="11" nRep="38" status="Passed" >
<Disp><![CDATA[Product Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf3.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:02]]></Time>
<TimeTick>1527009182</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:02]]></Time>
<TimeTick>1527009182</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[fetchImage?image_id=4700.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:02]]></Time>
<TimeTick>1527009182</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="42" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[fetchImage?image_id=4700.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[fetchImage?image_id=4700.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:05]]></Time>
<TimeTick>1527009185</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="45" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[fetchImage?image_id=4700.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="41" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="40" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Sub-Product Select]]></Obj>
<Details ><![CDATA[Click on the Product]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:05]]></Time>
<TimeTick>1527009185</TimeTick>
<NodeArgs eType="User" icon="11" nRep="46" status="Passed" >
<Disp><![CDATA[Sub-Product Select]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf4.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:29]]></Time>
<TimeTick>1527009209</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:29]]></Time>
<TimeTick>1527009209</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:29]]></Time>
<TimeTick>1527009209</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="50" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[save_to_cart.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:29]]></Time>
<TimeTick>1527009209</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="53" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="49" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj ><![CDATA[Add To Cart]]></Obj>
<Details ><![CDATA[Click on the cart button]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:29]]></Time>
<TimeTick>1527009209</TimeTick>
<NodeArgs eType="User" icon="11" nRep="54" status="Passed" >
<Disp><![CDATA[Add To Cart]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf5.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:39]]></Time>
<TimeTick>1527009219</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:39]]></Time>
<TimeTick>1527009219</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[check_out_btn.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:39]]></Time>
<TimeTick>1527009219</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="58" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[check_out_btn.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[check_out_btn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:39]]></Time>
<TimeTick>1527009219</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="61" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[check_out_btn.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="57" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping_3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" Source="Product_Select" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Check Out]]></Obj>
<Details ><![CDATA[Click on the Check Out button]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:39]]></Time>
<TimeTick>1527009219</TimeTick>
<NodeArgs eType="User" icon="11" nRep="62" status="Passed" >
<Disp><![CDATA[Check Out]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf6.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="5/22/2018 - 22:42:46" eTime="5/22/2018 - 22:43:49" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="30" status="Passed" >
<Disp><![CDATA[Product_Select Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T35">
<AName><![CDATA[Payment]]></AName>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:49]]></Time>
<TimeTick>1527009229</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:49]]></Time>
<TimeTick>1527009229</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[next_btn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:49]]></Time>
<TimeTick>1527009229</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[next_btn.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[safepay.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:49]]></Time>
<TimeTick>1527009229</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="71" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[safepay.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[safepay.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#0"]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:50]]></Time>
<TimeTick>1527009230</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="74" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[safepay.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="68" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="67" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj ><![CDATA[Safepay Radio]]></Obj>
<Details ><![CDATA[Click on the Safepay]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:50]]></Time>
<TimeTick>1527009230</TimeTick>
<NodeArgs eType="User" icon="11" nRep="75" status="Passed" >
<Disp><![CDATA[Safepay Radio]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf7.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:57]]></Time>
<TimeTick>1527009237</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:57]]></Time>
<TimeTick>1527009237</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[safepay_username.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:57]]></Time>
<TimeTick>1527009237</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="79" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[safepay_username.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[safepay_username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["iDeliver"]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:57]]></Time>
<TimeTick>1527009237</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="82" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[safepay_username.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="78" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="77" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[Safepay_username]]></Obj>
<Details ><![CDATA[Enter on the Safepay_username]]></Details>
<Time><![CDATA[5/22/2018 - 22:43:57]]></Time>
<TimeTick>1527009237</TimeTick>
<NodeArgs eType="User" icon="11" nRep="83" status="Passed" >
<Disp><![CDATA[Safepay_username]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf8.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:06]]></Time>
<TimeTick>1527009246</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:06]]></Time>
<TimeTick>1527009246</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[safepay_password.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:06]]></Time>
<TimeTick>1527009246</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="87" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[safepay_password.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[safepay_password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["iDeliver1"]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:07]]></Time>
<TimeTick>1527009247</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="90" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[safepay_password.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="86" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="85" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj ><![CDATA[Safepay_password]]></Obj>
<Details ><![CDATA[Enter on the Safepay_password]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:07]]></Time>
<TimeTick>1527009247</TimeTick>
<NodeArgs eType="User" icon="11" nRep="91" status="Passed" >
<Disp><![CDATA[Safepay_password]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf9.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:15]]></Time>
<TimeTick>1527009255</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:15]]></Time>
<TimeTick>1527009255</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[pay_now_btn_SAFEPAY.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:15]]></Time>
<TimeTick>1527009255</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="95" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[pay_now_btn_SAFEPAY.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[pay_now_btn_SAFEPAY.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:15]]></Time>
<TimeTick>1527009255</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="98" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[pay_now_btn_SAFEPAY.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="94" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="93" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj ><![CDATA[Pay_now]]></Obj>
<Details ><![CDATA[Click on the Pay_now]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:16]]></Time>
<TimeTick>1527009256</TimeTick>
<NodeArgs eType="User" icon="11" nRep="99" status="Passed" >
<Disp><![CDATA[Pay_now]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf10.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:24]]></Time>
<TimeTick>1527009264</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:24]]></Time>
<TimeTick>1527009264</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:24]]></Time>
<TimeTick>1527009264</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="104" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="103" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/22/2018 - 22:44:24]]></Time>
<TimeTick>1527009264</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="106" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="102" Source="Payment" SourceLine="-1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="5/22/2018 - 22:43:49" eTime="5/22/2018 - 22:44:25" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="64" status="Passed" >
<Disp><![CDATA[Payment Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Script Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="5/22/2018 - 22:42:32" eTime="5/22/2018 - 22:44:26" passed="10" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Script Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>